spring.application.name=proxy-service
spring.cloud.config.uri=http://ec2-16-171-42-48.eu-north-1.compute.amazonaws.com:8888
spring.config.import=configserver:
spring.cloud.config.fail-fast=true
management.endpoint.gateway.enabled=true
management.endpoints.web.exposure.include=*